name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  first job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        run: echo "Welcome you!"
      - name: list files
        run: ls
      - name: read file
        run: cat README.md
      