name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
  first job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        run: echo "Welcome you!"
      - name: list files
        run: ls
      - name: read file
        run: cat README.md
      