name: Execute a script

on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print comment
        run: |
            chmod +x hello.sh
            ./hello.sh

      